name: version1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get: ^3.17.1
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  firebase_auth: "^0.18.4+1"
  splashscreen: ^1.3.5
  google_fonts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    
    - images/oracle.jpg
    - images/shatta.jpg
  
    - images/men/clothings.jpg
    - images/men/newin.jpg
    - images/men/accessories.jpg
    - images/men/shoes.jpg
    - images/women/clothings.jpg
    - images/women/newin.jpg
    - images/women/accessories.jpg
    - images/women/shoes.jpg
    - images/clothes/tshirt.jpg
    - images/clothes/overall.jpg
    - images/clothes/skirt.jpg
    - images/clothes/sweater.jpg
    - images/clothes/dress.jpg
    - images/clothes/jeans.jpg
    - images/clothes/jacket.jpg
    - images/home.jpg
    - images/genderchoice.jpg
    - images/tshirts/tshirt1.webp
    - images/tshirts/tshirt2.webp
    - images/tshirts/tshirt3.webp
    - images/tshirts/tshirt4.webp
    - images/tshirts/tshirt5.webp
    - images/tshirts/tshirt6.webp
    - images/tshirts/tshirt7.webp
    - images/tshirts/tshirt8.webp
    - images/oip/pic1.jpg
    - images/oip/pic2.jpg
    - images/oip/pic3.jpg
    - images/oip/pic4.jpg
    - images/oip/pic5.jpg
    - images/oip/pic6.jpg
    - images/oip/pic7.jpg
    - images/oip/pic8.jpg
    - images/oip/pic9.jpg
    - images/oip/pic10.jpg
    - images/oip/pic11.jpg
    - images/oip/pic12.jpg
    - images/oip/pic13.jpg
    - images/oip/pic14.jpg
    - images/oip/pic15.jpg
    - images/oip/pic16.jpg
    - images/oip/pic16a.jpg
    - images/oip/pic17.jpg
    - images/oip/pic18.jpg





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
